mutation CreateKardexSale ( 
  $Cantidad: Float!
  $ProductoId: Int!
  $EnvaseId: Int!
  $FechaElaboracion: String!
  $Lote: String!
  $FechaVencimiento: String!
  $EnteId: Int!
  $FechaSale: String
  $NumeroFacturaSale: String
) {
  CreateKardexSale (
    Cantidad: $Cantidad
    ProductoId: $ProductoId
    EnvaseId: $EnvaseId
    FechaElaboracion: $FechaElaboracion
    Lote: $Lote
    FechaVencimiento: $FechaVencimiento
    EnteId: $EnteId
    FechaSale: $FechaSale
    NumeroFacturaSale: $NumeroFacturaSale
  ){
    Id
    Cantidad
    ProductoId
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
    EnvaseId
    Envase {
      Id
      NumeroInterno
      Capacidad
    }
    FechaElaboracion
    Lote
    FechaVencimiento
    EnteId
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    FechaSale
    NumeroFacturaSale
    FechaEntra
    NumeroFacturaEntra
  }
}
