mutation DeleteProduccion ( 
  $Id: Int!
) {
  DeleteProduccion (
    Id: $Id
  ){
    Id
    Orden
    Turno
    Fecha
    Lote
    FechaInicial
    FechaFinal
    HoraInicial
    HoraFinal
    FechaFabricacion
    FechaVencimiento
    Cantidad
    ProductoId
    EnvaseId
    PurezaFinal
    PresionFinal
    Observacion
    Despachado
    Envase {
      Id
      Numero
      Capacidad
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
    Cliente {
      Id
      Nombre
    }
  }
}
