query Kardexs (
  $Tipo: String,
  $EnteId: Int,
  $EnvaseId: Int,
  $FechaInicial: String,
  $FechaFinal: String
  ) {
  Kardexs (
    Tipo: $Tipo,
    EnteId: $EnteId,
    EnvaseId: $EnvaseId,
    FechaInicial: $FechaInicial,
    FechaFinal: $FechaFinal
  ) {
    Id
    Cantidad
    ProductoId
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
    EnvaseId
    Envase {
      Id
      Numero
      Capacidad
    }
    FechaElaboracion
    Lote
    FechaVencimiento
    EnteId
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    FechaSale
    NumeroFacturaSale
    FechaEntra
    NumeroFacturaEntra
  }
}
