query OneEnte($TipoDocumento: String!, $NumeroDocumento: String!) {
  OneEnte(TipoDocumento: $TipoDocumento, NumeroDocumento: $NumeroDocumento) {
    Id
    TipoDocumento
    NumeroDocumento
    Nombre
    Ciudad
    Direccion
    Telefono
    Relacion 
  }
}
