query Remisions ( 
  $Numero: String,
  $Fecha: String,
  $EnteId: Int
) {
  Remisions (
    Numero: $Numero, 
    Fecha: $Fecha,
    EnteId: $EnteId
  ){
    Id
    Numero
    Fecha
    EnteId
    ProduccionId
    EnvaseId
    Total
    Ente {
      Id
      TipoDocumento
      NumeroDocumento
      Nombre
      Ciudad
      Direccion
      Telefono
    }
    Produccion {
      Id
      Fecha
      Lote
      Cantidad
      Producto {
        Id
        Nombre
        UnidadDeMedida
      }
      FechaFabricacion
      FechaVencimiento
      Envase {
        Id
        Numero
        Capacidad
      }
    }
    Envase {
      Id
      Numero
    }
  }
}
