mutation UpdateProducto ( 
  $Nombre: String!, 
  $UnidadDeMedida: String,
) {
  UpdateProducto (
    Nombre: $Nombre,
    UnidadDeMedida: $UnidadDeMedida
  ){
    Id
    Nombre
    UnidadDeMedida
  }
}
