mutation UpdateOferta (
  $Id: Int,
  $ProveedorId: Int,
  $ProductoId: Int,
  $Cantidad: String,
  $Embalaje: Int,
  $Precio: Float,
  $Fecha: Float
){
  UpdateOferta (
    Id: $Id,
    ProveedorId: $ProveedorId,
    ProductoId: $ProductoId,
    Cantidad: $Cantidad,
    Embalaje: $Embalaje,
    Precio: $Precio,
    Fecha: $Fecha
  ) {
    Id
    ProveedorId
    ProductoId
    Cantidad
    Embalaje
    Precio
    Fecha
  }
}
