mutation UpdateProduccion ( 
  $Orden: String!,
  $Turno: String,
  $Fecha: String,
  $Lote: String,
  $FechaInicial: String,
  $FechaFinal: String,
  $HoraInicial: String,
  $HoraFinal: String,
  $FechaFabricacion: String!,
  $FechaVencimiento: String!,
  $Cantidad: Float!,
  $ProductoId: Int!,
  $EnvaseId: Int!,
  $ClienteId: Int!,
  $PurezaFinal: Float!,
  $PresionFinal: Float!
  $Observacion: String
) {
  UpdateProduccion (
    Orden: $Orden,
    Turno; $Turno,
    Fecha: $Fecha,
    Lote: $Lote,
    FechaInicial: $FechaInicial,
    FechaFinal: $FechaFinal,
    HoraInicial: $HoraInicial,
    HoraFinal: $HoraFinal,
    FechaFabricacion: $FechaFabricacion,
    FechaVencimiento: $FechaVencimiento,
    Cantidad: $Cantidad,
    ProductoId: $ProductoId,
    EnvaseId: $EnvaseId,
    ClienteId: $ClienteId,
    PurezaFinal: $PurezaFinal,
    PresionFinal: $PresionFinal,
    Observacion: $Observacion
  ){
    Id
    Orden
    Turno
    Fecha
    Lote
    FechaInicial
    FechaFinal
    HoraInicial
    HoraFinal
    FechaFabricacion
    FechaVencimiento
    Cantidad
    ProductoId
    EnvaseId
    ClienteId
    PurezaFinal
    PresionFinal
    Observacion
    Despachado
    Envase {
      Id
      Numero
      Capacidad
    }
    Producto {
      Id
      Nombre
      UnidadDeMedida
    }
    Cliente {
      Id
      Nombre
    }
  }
}
