mutation UpdateOferta (
  $Id: Int,
  $ProveedorId: Int,
  $ProductoId: Int,
  $LocalidadId: Int,
  $Cantidad: Float,
  $Embalaje: Float,
  $Precio: Float,
  $Fecha: String
){
  UpdateOferta (
    Id: $Id,
    ProveedorId: $ProveedorId,
    ProductoId: $ProductoId,
    LocalidadId: $LocalidadId,
    Cantidad: $Cantidad,
    Embalaje: $Embalaje,
    Precio: $Precio,
    Fecha: $Fecha
  ) {
    Id
    ProveedorId
    ProductoId
    LocalidadId
    Cantidad
    Embalaje
    Precio
    Fecha
  }
}
