mutation UpdateLocalidad (
  $Id: Int,
  $Codigo: String,
  $Nombre: String,
  $Poblacion: Int,
  $Altitud: Float,
  $Temperatura: Float
){
  UpdateLocalidad (
    Id: $Id,
    Codigo: $Codigo,
    Nombre: $Nombre,
    Poblacion: $Poblacion,
    Altitud: $Altitud,
    Temperatura: $Temperatura
  ) {
    Id
    Codigo
    Nombre
    Poblacion
    Altitud
    Temperatura
  }
}
