mutation UpdateDemanda (
  $Id: Int,
  $LocalidadId: Int,
  $ProductoId: Int,
  $ConsumoPromedio: Float,
  $Fecha: String
){
  UpdateDemanda (
    Id: $Id,
    LocalidadId: $LocalidadId,
    ProductoId: $ProductoId,
    ConsumoPromedio: $ConsumoPromedio,
    Fecha: $Fecha
  ) {
    Id
    LocalidadId
    ProductoId
    ConsumoPromedio
    Fecha
  }
}
